# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jotty < Formula
  desc "This tool to decode jwt tokens and print out the JSON"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "0.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/jotty/releases/download/v0.12/jotty_0.12_darwin_amd64.tar.gz"
      sha256 "775f04c225499e2fca1452df28e7a8a0d6b60f1fce5fefe0e1e51604763b7f22"

      def install
        bin.install "jotty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/jotty/releases/download/v0.12/jotty_0.12_darwin_arm64.tar.gz"
      sha256 "ed518bbaefbba61fc3e88f294e589a28683d8c9ac468cf4426f7f278c8a59e59"

      def install
        bin.install "jotty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/jotty/releases/download/v0.12/jotty_0.12_linux_amd64.tar.gz"
      sha256 "46094ec652f61c1be1a2d7216ab34fce22f9f01ffcc2a4e03dd81e0272172214"

      def install
        bin.install "jotty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/jotty/releases/download/v0.12/jotty_0.12_linux_arm64.tar.gz"
      sha256 "250311622af732439b9d62303d8558495c908a4ee75b52ede396d8fb1e6f65e3"

      def install
        bin.install "jotty"
      end
    end
  end
end
