# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jotty < Formula
  desc "This tool to decode jwt tokens and print out the JSON"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "1.01"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/jotty/releases/download/v1.01/jotty_1.01_darwin_arm64.tar.gz"
      sha256 "6541fa179213e7c9d844e74d208edf42878e840f1bf68c3abaf2a36d369db213"

      def install
        bin.install "jotty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/jotty/releases/download/v1.01/jotty_1.01_darwin_amd64.tar.gz"
      sha256 "b54ddfb367eec94f70c074a8d61b524ac283841aba8846e88ebe3c940938a616"

      def install
        bin.install "jotty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/jotty/releases/download/v1.01/jotty_1.01_linux_arm64.tar.gz"
      sha256 "191f2bc960f77465d8f92fbb11884cbc3ff4648599ed0d841e145ecf86ff8d31"

      def install
        bin.install "jotty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/jotty/releases/download/v1.01/jotty_1.01_linux_amd64.tar.gz"
      sha256 "ebe71f3575b8af77d1563eb5e3c92c6855f35e24b5dfb08e9d70bf73ed519c85"

      def install
        bin.install "jotty"
      end
    end
  end
end
